COMMAND = g++ -g -Wall -o PityBoy main.cpp -DSFML_STATIC -lsfml-graphics -lsfml-window -lsfml-system -lboost_filesystem -lboost_system -llua5.4 -static-libgcc -static-libstdc++

all: main.cpp
	$(COMMAND)